module.exports = {
  NEWS_API_KEY: "PASTE_YOUR_API_KEY_HERE",
  SPREAD_SHEET_ID: "PASTE_YOUR_SPREAD_SHEET_ID_HERE",
  AUTH_ID: "PASTE_YOUR_AUTH_ID_HERE",
  CLIENT_ID: "PASTE_YOUR_CLIENT_ID_HERE",
  SENDGRID_KEY: "PASTE_YOUR_SENDGRID_KEY_HERE",
  EMAIL_FROM_ADDRESS: "PASTE_FROM_EMAIL_HERE"
};
